package com.nn.safetransfer.transfer.api;

import com.nn.safetransfer.common.api.ErrorDto;
import com.nn.safetransfer.transfer.api.dto.CreateTransferRequest;
import com.nn.safetransfer.transfer.api.dto.TransferResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;

import java.util.UUID;

import static com.nn.safetransfer.common.api.ApiHeaders.IDEMPOTENCY_KEY;

@Tag(name = "Transfers", description = "Idempotent wallet-to-wallet money transfers.")
@RequestMapping("/api/v1/tenants/{tenantId}/transfers")
public interface TransferApi {

    @Operation(
            summary = "Create wallet-to-wallet transfer",
            description = """
                    Creates a transfer between two wallets in the same tenant and currency. The operation is idempotent:
                    reusing the same `Idempotency-Key` with the same request returns the existing transfer, while reusing
                    the key with a different request returns `409 Conflict`.
                    """
    )
    @ApiResponses({
            @ApiResponse(responseCode = "201", description = "Transfer created",
                    content = @Content(schema = @Schema(implementation = TransferResponse.class))),
            @ApiResponse(responseCode = "200", description = "Existing transfer returned for idempotent replay",
                    content = @Content(schema = @Schema(implementation = TransferResponse.class))),
            @ApiResponse(responseCode = "400", description = "Invalid request or currency mismatch",
                    content = @Content(schema = @Schema(implementation = ErrorDto.class))),
            @ApiResponse(responseCode = "404", description = "Source or destination wallet not found",
                    content = @Content(schema = @Schema(implementation = ErrorDto.class))),
            @ApiResponse(responseCode = "409", description = "Insufficient funds, inactive wallet, transfer limit exceeded, or idempotency conflict",
                    content = @Content(schema = @Schema(implementation = ErrorDto.class),
                            examples = @ExampleObject(name = "Idempotency conflict", value = """
                                    {"errorId":"018f1254-2f2c-7b54-9e6b-f30da9b0721e","errorMessage":"Idempotency key was already used with a different request body","errors":null}
                                    """)))
    })
    @PostMapping
    ResponseEntity<TransferResponse> createTransfer(
            @Parameter(description = "Tenant identifier.", example = "11111111-1111-1111-1111-111111111111")
            @PathVariable UUID tenantId,
            @Parameter(description = "Unique key generated by the client for safe retries.", example = "transfer-request-2026-04-18-0001")
            @RequestHeader(IDEMPOTENCY_KEY) String idempotencyKey,
            @Valid @RequestBody CreateTransferRequest request
    );

    @Operation(
            summary = "Get transfer",
            description = "Returns a transfer by tenant and transfer id."
    )
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Transfer found",
                    content = @Content(schema = @Schema(implementation = TransferResponse.class))),
            @ApiResponse(responseCode = "404", description = "Transfer not found",
                    content = @Content(schema = @Schema(implementation = ErrorDto.class)))
    })
    @GetMapping("/{transferId}")
    ResponseEntity<TransferResponse> getTransfer(
            @Parameter(description = "Tenant identifier.", example = "11111111-1111-1111-1111-111111111111")
            @PathVariable UUID tenantId,
            @Parameter(description = "Transfer identifier.", example = "33333333-3333-3333-3333-333333333333")
            @PathVariable UUID transferId
    );
}
